# Generated by Django 3.2.6 on 2021-09-14 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_title', models.CharField(default='', max_length=50)),
                ('p_head1', models.CharField(default='', max_length=500)),
                ('p_chead1', models.CharField(default='', max_length=5000)),
                ('p_head2', models.CharField(default='', max_length=500)),
                ('p_chead2', models.CharField(default='', max_length=5000)),
                ('p_head3', models.CharField(default='', max_length=500)),
                ('p_chead3', models.CharField(default='', max_length=5000)),
                ('p_date', models.DateField()),
                ('p_thumbnail', models.ImageField(default='', upload_to='blog/images')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('postsno', models.IntegerField(default=0)),
                ('postcomment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
