# Generated by Django 3.2.6 on 2021-09-15 06:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='p_chead3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='p_head3',
        ),
        migrations.AddField(
            model_name='post',
            name='p_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='p_body',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='p_date',
            field=models.DateTimeField(),
        ),
    ]
