# Generated by Django 3.2.6 on 2021-09-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_contact_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='p_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
