# Generated by Django 3.2.6 on 2021-09-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_p_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='p_chead1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='p_chead2',
            field=models.TextField(),
        ),
    ]
