# Generated by Django 3.2.6 on 2021-09-18 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210918_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='p_thumbnail',
        ),
    ]
