# Generated by Django 3.2.6 on 2021-09-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_post_p_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='p_thumbnail',
            field=models.ImageField(default='', upload_to='blog/images'),
        ),
    ]
